### ISSUE TITLE
feat: Smaller bundle size

### ISSUE THREAD

**Issue by lcottercertinia** [certinia/debug-log-analyzer#226]
- [x] Minify html
[Building: Rollup Plugin HTML: Modern Web](https://modern-web.dev/docs/building/rollup-plugin-html/)
Move the page out of dist and have it copied there as a minified version using rollup
- [x] replace tslib with swc helper
[ts-node — Use SWC to Speed up TypeScript Code](https://futurestud.io/tutorials/ts-node-use-swc-to-speed-up-typescript-code)
- [ ] Could apex-ls be smaller? or maybe we should split it and lazy load when needed?
- [ ] Ensure all deps have an es6 version on npm (small bundle, faster bundling due to no commonjs to es6 convert)
- [ ] [Jsforce](https://github.com/jsforce/jsforce/tree/2.0) - switch to inquirer prompt package instead of inquirer (much smaller)

### Other actions

- Use the bundle Analyzer to target places that can be trimmed or switched to named imports
- Lazy load apex-ls and other large deps that are not immediately needed. Can use code splitting for this.
- Remove duplicate npm packages (Use the bundle analyse to find duplicates to address)
- Only import the parts of tabulator we need, instead of everything

**Comment by lcottercertinia** [comment]
Most of these have been done. More specific issues shoulder be created for future work.
